### ISSUE TITLE
flowview_upgrade give missing cell, and table exist

### ISSUE THREAD

**Issue by arno-st** [Cacti/plugin_flowview#199]
I just give you that like that, didn't have the time now to check on it.

09/08/2024 14:57:59 - FLOWVIEW Flowview Database Upgrade Complete
--
09/08/2024 14:57:59 - CMDPHP SQL Backtrace:   (/plugins/flowview/flowview_upgrade.php[98]:flowview_upgrade(),  /plugins/flowview/flowview_upgrade.php[479]:flowview_db_execute(),  /plugins/flowview/database.php[70]:db_execute(),  /lib/database.php[385]:db_execute_prepared())
09/08/2024 14:57:59 - CMDPHP ERROR: A DB Exec Failed!, Error:  Unknown column 'origin_as' in 'plugin_flowview_arin_information'
09/08/2024 14:57:59 - CMDPHP SQL Backtrace:   (/plugins/flowview/flowview_upgrade.php[98]:flowview_upgrade(),  /plugins/flowview/flowview_upgrade.php[476]:include_once(),  /plugins/flowview/irr_tables.php[133]:flowview_db_execute(),  /plugins/flowview/database.php[70]:db_execute(),  /lib/database.php[385]:db_execute_prepared())
09/08/2024 14:57:59 - CMDPHP ERROR: A DB Exec Failed!, Error: You  have an error in your SQL syntax; check the manual that corresponds to  your MariaDB server version for the right syntax to use near 'KEY  `source` (`source`)) ENGINE=Aria ROW_FORMAT=Page COMMENT='Contains  inform...' at line 1
09/08/2024 14:57:59 - CMDPHP SQL Backtrace:   (/plugins/flowview/flowview_upgrade.php[98]:flowview_upgrade(),  /plugins/flowview/flowview_upgrade.php[446]:flowview_db_execute(),  /plugins/flowview/database.php[70]:db_execute(),  /lib/database.php[385]:db_execute_prepared())
09/08/2024 14:57:59 - CMDPHP ERROR: A DB Exec Failed!, Error: You  have an error in your SQL syntax; check the manual that corresponds to  your MariaDB server version for the right syntax to use near 'unsigned  NOT NULL DEFAULT '', `map_partition` varchar(20) NOT NULL DEFAULT ''...'  at line 1
09/08/2024 14:57:59 - CMDPHP SQL Backtrace:   (/plugins/flowview/flowview_upgrade.php[98]:flowview_upgrade(),  /plugins/flowview/flowview_upgrade.php[442]:flowview_db_execute(),  /plugins/flowview/database.php[70]:db_execute(),  /lib/database.php[385]:db_execute_prepared())
09/08/2024 14:57:59 - CMDPHP ERROR: A DB Exec Failed!, Error: Duplicate column name 'full_scan'
09/08/2024 14:57:59 - CMDPHP SQL Backtrace:   (/plugins/flowview/flowview_upgrade.php[98]:flowview_upgrade(),  /plugins/flowview/flowview_upgrade.php[429]:flowview_db_execute(),  /plugins/flowview/database.php[70]:db_execute(),  /lib/database.php[385]:db_execute_prepared())
09/08/2024 14:57:59 - CMDPHP ERROR: A DB Exec Failed!, Error: Duplicate column name 'cached_shards'
09/08/2024 14:57:59 - CMDPHP SQL Backtrace:   (/plugins/flowview/flowview_upgrade.php[98]:flowview_upgrade(),  /plugins/flowview/flowview_upgrade.php[424]:flowview_db_execute(),  /plugins/flowview/database.php[70]:db_execute(),  /lib/database.php[385]:db_execute_prepared())
09/08/2024 14:57:59 - CMDPHP ERROR: A DB Exec Failed!, Error: Duplicate column name 'md5sum_tables'
09/08/2024 14:57:59 - CMDPHP SQL Backtrace:   (/plugins/flowview/flowview_upgrade.php[98]:flowview_upgrade(),  /plugins/flowview/flowview_upgrade.php[418]:flowview_db_execute(),  /plugins/flowview/database.php[70]:db_execute(),  /lib/database.php[385]:db_execute_prepared())
09/08/2024 14:57:59 - CMDPHP ERROR: A DB Exec Failed!, Error: Duplicate column name 'map_range'
09/08/2024 14:57:59 - CMDPHP SQL Backtrace:   (/plugins/flowview/flowview_upgrade.php[98]:flowview_upgrade(),  /plugins/flowview/flowview_upgrade.php[401]:flowview_db_execute(),  /plugins/flowview/database.php[70]:db_execute(),  /lib/database.php[385]:db_execute_prepared())
09/08/2024 14:57:59 - CMDPHP ERROR: A DB Exec Failed!, Error: You  have an error in your SQL syntax; check the manual that corresponds to  your MariaDB server version for the right syntax to use near 'unsigned  NOT NULL DEFAULT '', `map_partition` varchar(20) NOT NULL DEFAULT ''...'  at line 1
09/08/2024 14:57:58 - CMDPHP SQL Backtrace:   (/plugins/flowview/flowview_upgrade.php[98]:flowview_upgrade(),  /plugins/flowview/flowview_upgrade.php[253]:db_execute(),  /lib/database.php[385]:db_execute_prepared())
09/08/2024 14:57:58 - CMDPHP ERROR: A DB Exec Failed!, Error: Table 'reports_queued' already exists
09/08/2024 14:57:58 - CMDPHP SQL Backtrace:   (/plugins/flowview/flowview_upgrade.php[98]:flowview_upgrade(),  /plugins/flowview/flowview_upgrade.php[227]:db_column_exists(),  /lib/database.php[1124]:db_fetch_cell(),  /lib/database.php[576]:db_fetch_cell_prepared(),  /lib/database.php[598]:db_execute_prepared())
09/08/2024 14:57:58 - CMDPHP ERROR: A DB Cell Failed!, Error: Table 'cacti_test.sent_by' doesn't exist
09/08/2024 14:57:58 - FLOWVIEW Updating template_id column to plugin_flowview_queries table to signed.
09/08/2024 14:57:58 - FLOWVIEW Upgrading from v3.3 to 4.8

**Comment by TheWitness** [comment]
Man, I must have been 'sleep coding' when I did this.  Fixing shortly.

**Comment by TheWitness** [comment]
Should be resolved now.

**Comment by arno-st** [comment]
Well somehow you delete my pull request #197 
And that give me some error again, and still the #196 is  not resolved
I got this error when I view all filter
`
12/08/2024 12:08:50 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/flowview/flowview_filters.php[68]:show_filters(), /plugins/flowview/flowview_filters.php[379]:CactiErrorHandler())
12/08/2024 12:08:50 - ERROR PHP WARNING in Plugin 'flowview': Trying to access array offset on value of type null in file: /usr/share/cacti/plugins/flowview/flowview_filters.php on line: 379
12/08/2024 12:08:50 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/flowview/flowview_filters.php[68]:show_filters(), /plugins/flowview/flowview_filters.php[379]:CactiErrorHandler())
12/08/2024 12:08:50 - ERROR PHP WARNING in Plugin 'flowview': Undefined array key 0 in file: /usr/share/cacti/plugins/flowview/flowview_filters.php on line: 379
`

And when i edit a filter without report I got this one:
```
12/08/2024 12:10:38 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/flowview/flowview_filters.php[59]:edit_filter(), /plugins/flowview/functions.php[225]:CactiErrorHandler())
12/08/2024 12:10:38 - ERROR PHP WARNING in Plugin 'flowview': Undefined array key 0 in file: /usr/share/cacti/plugins/flowview/functions.php on line: 225

```
I saw your code, but it

**Comment by arno-st** [comment]
Okay no more error of this type
