### ISSUE TITLE
Problem with ` symbol in SQL queries

### ISSUE THREAD

**Issue by kubafalta** [Cacti/plugin_flowview#62]
Hi,

I have problem with ` symbol in some SQL queries in Flowview 3.2 in Cacti 1.2.4 on CentOS 7 with MariaDB 10.1.41.

It occurs for example when I choose some protocol in filter and then I use this filter.
There are these messages in log:

2020/12/18  10:48:08 - CMDPHP SQL Backtrace:   (/plugins/flowview/flowview.php[50]:flowview_get_chartdata(),  /plugins/flowview/functions.php[1529]:run_flow_query(),  /plugins/flowview/functions.php[2172]:db_fetch_assoc(),  /lib/database.php[476]:db_fetch_assoc_prepared(),  /lib/database.php[490]:db_execute_prepared())
--
2020/12/18 10:48:08 - CMDPHP ERROR: A DB Row Failed!, Error: You  have an error in your SQL syntax; check the manual that corresponds to  your MariaDB server version for the right syntax to use near 'AND  `protocol` IN (6) GROUP BY src_addr, dst_addr UNION SELECT src_addr,  dst_add' at line 1

Is there some problem with DB encoding or in query creating?

**Comment by TheWitness** [comment]
Well, I've been having the same issue, and banging my head against the wall.  You should run the following script.  Do it once a day

```sh
cd /var/www/html/cacti/cli
php convert_tables.php --innodb --utf8 --size=10000000 --dynamic
```

For some reason, the tables are getting utf8mb4_general_ci instead of utf8mb4_unicode_ci at create time which is causing this issue.  Blows my mind as to how it's happening.

**Comment by TheWitness** [comment]
I've committed a change to flowview/functions.php to work around this problem near term.  But, before you close this, run the command above, then download the file.  Once you stop receiving these warnings, you can close this.

**Comment by kubafalta** [comment]
I executed the command and change file but it is still the same.
I'm looking at my previous comment and ` symbol is missing in SQL because it formated word **protocol**.

use near 'AND \`protocol\` IN (6) GROUP BY src_addr, dst_addr UNION SELECT src_addr, dst_add' at line 1

**Comment by TheWitness** [comment]
That's not the problem.  Goto line 2167 in functions.php and uncomment it.  Then run your query again and post the entirety of the output in the cacti.log.

**Comment by kubafalta** [comment]
2020/12/18  20:08:08 - CMDPHP SQL Backtrace:   (/plugins/flowview/flowview.php[50]:flowview_get_chartdata(),  /plugins/flowview/functions.php[1529]:run_flow_query(),  /plugins/flowview/functions.php[2172]:db_fetch_assoc(),  /lib/database.php[476]:db_fetch_assoc_prepared(),  /lib/database.php[490]:db_execute_prepared())
2020/12/18 20:08:08 - CMDPHP ERROR: A DB Row Failed!, Error: You  have an error in your SQL syntax; check the manual that corresponds to  your MariaDB server version for the right syntax to use near 'AND  \`protocol\` IN (6) GROUP BY src_addr) AS rs GROUP BY INET6_NTOA(src_addr)   OR' at line 1
2020/12/18 20:08:08 - CMDPHP SELECT INET6_NTOA(src_addr) AS  src_addr, SUM(flows) AS flows, SUM(bytes) AS bytes, SUM(packets) AS  packets, src_domain FROM (SELECT src_addr, SUM(flows) AS flows,  SUM(bytes) AS bytes, SUM(packets) AS packets, src_domain FROM  plugin_flowview_raw_202035220  AND \`protocol\` IN (6) GROUP BY src_addr)  AS rs GROUP BY INET6_NTOA(src_addr)  ORDER BY 4 DESC LIMIT 50

**Comment by TheWitness** [comment]
That helped.  Are you using the release tag or develop?

**Comment by kubafalta** [comment]
Develop.

**Comment by TheWitness** [comment]
Okay, scratched my head, but it's fixed now.  Back from the XMas holiday.

**Comment by kubafalta** [comment]
Thanks a lot. It is ok now.
